trigger:
- none

parameters:
  - name: tag
    type: string
    default: 'latest'

variables:
  imageRepository: 'cloudsample'
  containerRegistry: 'cepgstapacr.azurecr.io'
  #tag: '$(Build.BuildId)'
  #tag: 0.0.1-SNAPSHOT.20240725.2

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo "version : ${{ parameters.tag }}"
      
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'cepg-aa-std-aks-clstr'
    namespace: 'default'
    manifests: |
      $(Pipeline.Workspace)/s/manifests/deployment.yml
      $(Pipeline.Workspace)/s/manifests/service.yml
      $(Pipeline.Workspace)/s/manifests/ingress.yml
    containers: |
      $(containerRegistry)/$(imageRepository):${{ parameters.tag }}
