trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'cepg-aa-std-aks-clstr'
    namespace: 'default'
    manifests: |
      $(Pipeline.Workspace)/manifests/deployment.yml
      $(Pipeline.Workspace)/manifests/service.yml
    containers: |
      $(containerRegistry)/$(imageRepository):$(tag)
