trigger:
- none

variables:
  imageRepository: 'cloudsample'
  containerRegistry: 'cepgstapacr.azurecr.io'
  #tag: '$(Build.BuildId)'
  tag: 0.0.1-SNAPSHOT.20240725.1

pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'cepg-aa-std-aks-clstr'
    namespace: 'default'
    manifests: |
      $(Pipeline.Workspace)/s/manifests/deployment.yml
      $(Pipeline.Workspace)/s/manifests/service.yml
    containers: |
      $(containerRegistry)/$(imageRepository):$(tag)
