spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"