apiVersion : apps/v1
kind: Deployment
metadata:
  name: cloudsample 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsample
  template:
    metadata:
      labels:
        app: cloudsample 
    spec:
      containers:
        - name: cloudsample 
          image: cepgstapacr.azurecr.io/cloudsample
          ports:
          - containerPort: 8080
        voiumeMounts:
          - mountPath: /mnt/cloud-sample
            name: cloud-sample-volume
            readOnly: false
            subPath: cloud-sample
      volumes:
        - name: cloud-sample-volume
          persistentVolumeClaim:
            claimName: cepg-aa-std-pvc