name: Test Version
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: test
        run: |
          echo 'sha: ${{ github.sha }}';
          echo date: `date +%Y%m%d%H%M`;
